# Generated by Django 3.1.5 on 2021-01-26 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_name', models.CharField(max_length=50, verbose_name='Производитель')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('vendor_code', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Артикул')),
                ('model_name', models.CharField(max_length=100, verbose_name='Модель')),
                ('dealer_price', models.PositiveIntegerField(verbose_name='Дилер UAH')),
                ('retail_price', models.PositiveIntegerField(blank=True, verbose_name='РРЦ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.manufacturer')),
            ],
        ),
    ]
