# Generated by Django 3.1.5 on 2021-01-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210126_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='retail_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='РРЦ'),
        ),
    ]
