# Generated by Django 3.1.5 on 2021-01-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210127_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vendor_code',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Артикул'),
        ),
    ]
